---
- hosts: all
  become_user: root
  become: yes

  tasks:

  - name: create folder
    file:
      path: /home/ubuntu/prueba
      state: directory
      owner: root
      group: root
      mode: 0775
