---
- hosts: all
  become_user: oracle
  become: yes
  tasks:

  - name: create folder
    file:
      path: /home/oracle/prueba
      state: directory
      owner: oracle
      group: oinstall
      mode: 0775
