---
- hosts: all
  become_user: oracle
  become: yes
  tasks:


  - name: Execute Create DB User
    shell:
      cmd: |
        touch /tmp/createuser.out
        source /home/oracle/.bash_profile
        sqlplus -S "/ as sysdba" << EOF        
        spool /tmp/createuser.out
        alter session set container = INSISDB;
        create user {{db_user}} identified by "{{db_password}}";
        grant create session to {{db_user}};
        grant select any table to {{db_user}};
        EOF
        touch /tmp/createuser_{{db_user}}.done
    args:
      creates: /tmp/createuser_{{db_user}}.done

  - name: Save output
    command: cat /tmp/createuser.out
    register: createuser_command_output

  - name: Print to console
    debug:
      msg: "{{ createuser_command_output.stdout }}"
  
  - name: Remove .done control file
    file:
      path: /tmp/createuser_{{db_user}}.done
      state: absent

  - name: Remove .out control file
    file:
      path: /tmp/createuser.out
      state: absent  
  
  
