---
- hosts: all
  become_user: oracle
  become: yes
  tasks:

  
  - name: Execute Create DB User
    shell:
      cmd: |
        touch /tmp/createuser.out
        source /home/oracle/.bash_profile
        sqlplus -S "/ as sysdba" << EOF        
        spool /tmp/createuser.out
        alter session set container = INSISDB;
        create user {{USUARIO}} identified by "{{PASSWORD}}";
        grant create session to {{USUARIO}};
        grant select any table to {{USUARIO}};
        EOF
        touch /tmp/createuser_{{USUARIO}}.done
    args:
      creates: /tmp/createuser_{{USUARIO}}.done

  - name: Save output
    command: cat /tmp/createuser.out
    register: createuser_command_output

  - name: Print to console
    debug:
      msg: "{{ createuser_command_output.stdout }}"
  
  - name: Remove .done control file
    file:
      path: /tmp/createuser_{{USUARIO}}.done
      state: absent

  - name: Remove .out control file
    file:
      path: /tmp/createuser.out
      state: absent  
  
  
