---
- hosts: all
  become_user: oracle
  become: yes
  tasks:

  - name: create archivo
    shell:
        cmd: |
           cd /home/oracle/prueba/
           touch prueba.txt
           echo "Hello word" > prueba.txt
