---
- hosts: all
  become_user: root
  become: yes

  tasks: 
  - name: Eliminar .tar
    shell: find /GITRelease/ -user root \( \-name '*.tar' \) -exec rm {} \;

  - name: Delete branch directory
    file:
      path: /GITRelease/{{ branch }}
      state: absent
      
  - name: create folder
    file:
      path: /GITRelease/{{ branch }}
      state: directory
      owner: root
      group: root
      mode: 0775 

  - name: download branch in folder
    shell:
      cmd: |
        cd /GITRelease/{{ branch }}
        git clone --branch release/{{ branch }} https://github.com/lizy1987/BD.git
          
  - name: compress all the files in tar
    archive:
      path: "/GITRelease/{{ branch }}/BD/DB/"
      dest: /GITRelease/{{ branch }}/BD/DB/{{ branch }}.tar
      format: tar      