---
- hosts: all
  become_user: oracle
  become: yes
  vars:
    stepname1: fix-invalid-objects
    stepname2: check-invalid-objects

  tasks:  
  - name: execute sql
    include_role:
      name: bd-execute-sql
    vars:
      sql_script: fix-invalid-objects
      stepname: "{{ stepname1 }}"
      
  - name: Save output
    command: cat /home/oracle/salida{{ stepname1 }}.out
    register: fix_command_output

  - name: Print to console
    debug:
      msg: "{{ fix_command_output.stdout }}"

  - name: Remove .done control file
    file:
      path: /home/oracle/{{ stepname1 }}.done
      state: absent

  - name: Remove .out control file
    file:
      path: /home/oracle/salida{{ stepname1 }}.out
      state: absent  

  - name: execute sql
    include_role:
      name: bd-execute-sql
    vars:
      sql_script: check-invalid-objects
      stepname: "{{ stepname2 }}"
      
  - name: Save output
    command: cat /home/oracle/salida{{ stepname2 }}.out
    register: check_command_output

  - name: Print to console
    debug:
      msg: "{{ check_command_output.stdout }}"

  - name: Remove .done control file
    file:
      path: /home/oracle/{{ stepname2 }}.done
      state: absent

  - name: Remove .out control file
    file:
      path: /home/oracle/salida{{ stepname2 }}.out
      state: absent