---
- hosts: all
  become_user: oracle
  become: yes
  tasks:

  - name: Copy SQL Create DB User Template
    include_role:
        name: copy-file
    vars:
      user_execution: oracle
      mode_copy: 0644
      source_template: crearUsuario.sql.j2
      destination_template_path: /home/oracle/ 
      destination_template: crearUsuario.sql

  - name: Execute Create DB User
    shell:
      cmd: |
        touch /tmp/createuser.out
        source /home/oracle/.bash_profile
        sqlplus -S "/ as sysdba" << EOF        
        spool /tmp/createuser.out
        @/home/oracle/crearUsuario.sql
        EOF
        touch /tmp/createuser_{{db_user}}.done
    args:
      creates: /tmp/createuser_{{db_user}}.done

  - name: Save output
    command: cat /tmp/createuser.out
    register: createuser_command_output

  - name: Print to console
    debug:
      msg: "{{ createuser_command_output.stdout }}"
  
  - name: Remove .done control file
    file:
      path: /tmp/createuser_{{db_user}}.done
      state: absent

  - name: Remove .out control file
    file:
      path: /tmp/createuser.out
      state: absent  
  
  
